//
// Created by adrianoii on 23/07/2021.
//

#ifndef GCC_EXCEPTION_H
#define GCC_EXCEPTION_H

typedef enum
{
    EMPTY_EXCEPTION,
    FAILED_AT_EXIT,
    ALLOCATION_FAILED,
    INVALID_CLI,
    INVALID_FILE,
    INVALID_FILE_ROLLBACK_CHAR,
    LEX_INVALID_BRACKET_COMMENT,
    LEX_INVALID_SLASH_COMMENT,
    LEX_INVALID_INT,
    LEX_INVALID_FLOAT,
    LEX_INVALID_SYMBOL,
    ASSERT_FAIL,
    INVALID_CHAR_FROM_FILE,
    INVALID_LEXICAL_ERROR_STATE,
    INVALID_LEXICAL_PARSER_STATE,
    SYN_ERROR,
    ST_ID_NOT_FOUND,
    ST_INVALID_PARAM_ARG,
    ST_INVALID_TYPE_ENTRY,
    ST_PROC_ALREADY_DECLARED,
    ST_VAR_ALREADY_DECLARED,
    SEM_INCOMPATIBLE_TYPES,
    SEM_INVALID_ARGUMENTS,
    SEM_PROCEDURE_NESTING,
    RT_DIVISION_BY_ZERO,
    RT_MISSING_INPP,
    CG_INVALID_INSTRUCTION,
    INVALID_FLOAT_ARCH,
    INVALID_SIZE_T_ARCH,
    INVALID_INT_ARCH,
} exception_t;

#endif //GCC_EXCEPTION_H
