//
// Created by adrianoii on 23/07/2021.
//

#ifndef GCC_EXCEPTION_H
#define GCC_EXCEPTION_H

typedef enum
{
    EMPTY_EXCEPTION,
    ALLOCATION_FAILED,
    INVALID_CLI,
    INVALID_FILE,
    INVALID_FILE_ROLLBACK_CHAR,
    LEX_INVALID_BRACKET_COMMENT,
    LEX_INVALID_SLASH_COMMENT,
    LEX_INVALID_FLOAT,
    LEX_INVALID_SYMBOL,
    ASSERT_FAIL,
    INVALID_CHAR_FROM_FILE,
    INVALID_LEXICAL_ERROR_STATE,
    INVALID_LEXICAL_PARSER_STATE,
    SYN_ERROR,
} exception_t;

#endif //GCC_EXCEPTION_H
